add nightly flag to bin/doc (#34886)
Runs `bin/doc` using nightly channel. 

### Motivation

`bin/doc` fails locally as the -Z flag requires nightly (it gets run as
part of `misc/githooks/pre-push`)

```
materialize % bin/doc
cargo doc failed:
error: the `-Z` flag is only accepted on the nightly channel of Cargo, but this is the `stable` channel
See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.
```