adapter: Fix copy from stdin with concurrent table drops (#35258)
Seen in
https://buildkite.com/materialize/nightly/builds/15389#019ca015-4168-4db0-b1c0-7c150f06b96c

```
thread 'coordinator' panicked at src/adapter/src/catalog/state.rs:740:32: catalog out of sync, missing id User(1604)
```

Triggered 10 parallel-workload runs to verify