10006 [Planner] Add error in planning for unsupported range types (#34926)
## Problem:
Using an unsupported type with ranges (e.g., float) leads to a panic in
either the optimizer or execution:
```
ERROR: internal error: internal error in optimizer: internal transform error: unexpected panic during query optimization: internal error: entered unreachable code: UInt16(1) not yet supported in ranges
```

## Solution:
Introduce a new error in get_cast that validates the range type
(validate_range_element_type) to only the allowed range types (int32,
int64, date, numeric, timestamp:
https://www.postgresql.org/docs/current/rangetypes.html)

Introduce this in get_cast because this is used in the planning phase.
If we simply introduce an error in the actual evaluation (e.g., in
RangeBound::canonicalize) then it is possible that if the table is
empty, an error is not thrown

## Testing:
New tests in range.slt that tests ranges with uint2 and floats.

### Motivation

  * This PR fixes a recognized bug.

https://github.com/MaterializeInc/database-issues/issues/10065